"""
Django settings for TeleAgent project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_INSECURE_SECRET_KEY = 'django-insecure-w1-w6mc!)ddwdin!9h)z28oasvsoho@ktu55h2%o%8c4v&u7v&'
SECRET_KEY = os.environ.get('SECRET_KEY', _INSECURE_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# 生产环境（DEBUG=False）拒绝以内置/占位/过短的 SECRET_KEY 启动，强制通过环境变量注入真正的密钥。
if not DEBUG:
    from django.core.exceptions import ImproperlyConfigured
    if SECRET_KEY == _INSECURE_SECRET_KEY or 'CHANGE_ME' in SECRET_KEY or len(SECRET_KEY) < 32:
        raise ImproperlyConfigured(
            "生产环境必须通过环境变量设置一个强 SECRET_KEY（不能是内置默认值/占位符，长度≥32）。"
            "例如：python -c \"import secrets;print(secrets.token_urlsafe(50))\""
        )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'OnlineBroker',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'OnlineBroker.middleware.BrokerCSRFExemptMiddleware',  # /api/broker/ 强制豁免 CSRF
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TeleAgent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TeleAgent.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
_POSTGRES_HOST = os.environ.get('POSTGRES_HOST')
if _POSTGRES_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'postgres'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': _POSTGRES_HOST,
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            'OPTIONS': {'connect_timeout': 10},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.environ.get('STATIC_ROOT', str(BASE_DIR / 'staticfiles'))

# Media（文件传输落盘）。生产应挂到数据卷；下载经鉴权视图流式返回，不直接暴露静态目录。
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media'))
MEDIA_URL = 'media/'
# 单个文件传输的大小上限（字节），默认 50MB；超出拒绝（base64 中转，过大不适合）。
FILE_TRANSFER_MAX_BYTES = int(os.environ.get('FILE_TRANSFER_MAX_BYTES', str(50 * 1024 * 1024)))
# 文件传输有效期（小时），过期由清理命令删除。
FILE_TRANSFER_TTL_HOURS = int(os.environ.get('FILE_TRANSFER_TTL_HOURS', '24'))
# base64 中转需放宽 DRF/Django 的请求体上限（约为文件大小的 4/3 再留余量）。
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', str(FILE_TRANSFER_MAX_BYTES * 2))
)

# CSRF / HTTPS (for reverse proxy)
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # broker 客户端 Token（每条凭证专属，最小授权）。与下面的 TokenAuthentication 同用
        # 关键字 "Token"，必须排在其前：本类对非 broker Token 返回 None 回退，由 TokenAuthentication
        # 校验用户主 Token，从而两类 Token 在所有 broker 端点皆可用。
        'OnlineBroker.authentication.BrokerClientTokenAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# 日志配置 - 使用环境变量
def parse_log_size(size_str: str) -> int:
    """
    Parse log size string, e.g. '10MB' -> bytes.
    Defaults to 10MB when empty or invalid.
    """
    if not size_str:
        return 10 * 1024 * 1024

    size_str = str(size_str).strip().upper()
    try:
        if size_str.endswith("MB"):
            return int(size_str[:-2]) * 1024 * 1024
        if size_str.endswith("KB"):
            return int(size_str[:-2]) * 1024
        if size_str.endswith("GB"):
            return int(size_str[:-2]) * 1024 * 1024 * 1024
        return int(size_str)  # assume plain bytes
    except (TypeError, ValueError):
        return 10 * 1024 * 1024


LOG_LEVEL_ENV = os.environ.get("LOG_LEVEL", "DEBUG")
LOG_MAX_SIZE = parse_log_size(os.environ.get("LOG_MAX_SIZE", "10MB"))
LOG_BACKUP_COUNT = int(os.environ.get("LOG_BACKUP_COUNT", "100") or 100)
LOG_FORMAT_ENV = os.environ.get("LOG_FORMAT", "verbose")

# Log directory
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime}-{levelname}-{module}-{process:d}-{thread:d}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'console': {
            'format': '%(asctime)s - %(thread)d - %(name)s - %(levelname)s - %(message)s',
        },
        'json': {
            'format': '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s", "process": %(process)d, "thread": %(thread)d}',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': LOG_LEVEL_ENV,
            'class': 'logging.StreamHandler',
            'formatter': LOG_FORMAT_ENV,
            'filters': ['require_debug_true'],
        },
        'file': {
            'level': LOG_LEVEL_ENV,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'teleagent.log'),
            'maxBytes': LOG_MAX_SIZE,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'teleagent_error.log'),
            'maxBytes': LOG_MAX_SIZE * 5,
            'backupCount': LOG_BACKUP_COUNT * 2,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': LOG_LEVEL_ENV,
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'urllib3': {
            'handlers': ['file', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'requests': {
            'handlers': ['file', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'PIL': {
            'handlers': ['file', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'matplotlib': {
            'handlers': ['file', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# 确保日志目录存在
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)