# Generated by Django 4.2.20 on 2026-03-05 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OnlineBroker', '0002_add_agent_client_and_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentclient',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='所属用户，未登录注册的客户端为 null（兼容旧数据）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='所属用户；未登录创建的为 null（兼容旧数据）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
