# Generated by Django 4.2.20 on 2026-03-05 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OnlineBroker', '0003_add_owner_to_conversation_and_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerClientCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='备注名，如「Neal 的笔记本」', max_length=128)),
                ('secret_hash', models.CharField(help_text='Secret Key 的哈希，不存明文', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='该凭证登录后代表的用户（会话与客户端归属此用户）', on_delete=django.db.models.deletion.CASCADE, related_name='broker_client_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker 客户端凭证',
                'verbose_name_plural': 'Broker 客户端凭证',
                'ordering': ['-created_at'],
            },
        ),
    ]
