# Generated by Django 4.2.20 on 2026-06-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBroker', '0010_purge_plaintext_secret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentclient',
            options={'ordering': ['-last_seen', '-created_at'], 'verbose_name': 'Agent 客户端', 'verbose_name_plural': 'Agent 客户端'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': '会话', 'verbose_name_plural': '会话'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': '消息', 'verbose_name_plural': '消息'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(help_text='任务内自增序号（从 1 开始），用于增量拉取与去重')),
                ('payload', models.JSONField(help_text='单条归一化事件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rows', to='OnlineBroker.task')),
            ],
            options={
                'verbose_name': '任务事件',
                'verbose_name_plural': '任务事件',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['task', 'seq'], name='OnlineBroke_task_id_61303b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='taskevent',
            constraint=models.UniqueConstraint(fields=('task', 'seq'), name='uniq_task_event_seq'),
        ),
    ]
