# Generated by Django 4.2.20 on 2026-06-22 13:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBroker', '0013_agent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('set_permission_mode', '切换权限模式'), ('set_model', '切换模型'), ('interrupt', '中断当前执行')], max_length=32)),
                ('value', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', '待应用'), ('applied', '已应用'), ('failed', '失败')], default='pending', max_length=16)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='OnlineBroker.conversation')),
            ],
            options={
                'verbose_name': '会话控制指令',
                'verbose_name_plural': '会话控制指令',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'status'], name='OnlineBroke_convers_9d45f1_idx')],
            },
        ),
    ]
