# Generated by Django 5.2.9 on 2026-06-28 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBroker', '0014_conversationcontrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokerclientcredential',
            name='secret_value',
        ),
    ]
