# Generated by Django 5.2.9 on 2026-06-28 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBroker', '0015_drop_plaintext_secret_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='FsBrowseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, help_text='请求列出的目录；空表示该机用户主目录', max_length=4096)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('done', '已完成'), ('failed', '失败')], default='pending', max_length=16)),
                ('listed_path', models.CharField(blank=True, max_length=4096)),
                ('parent_path', models.CharField(blank=True, max_length=4096, null=True)),
                ('entries', models.JSONField(blank=True, default=list, help_text='子项列表：[{name, path, is_dir}]')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(help_text='要浏览哪台 PC 的目录', on_delete=django.db.models.deletion.CASCADE, related_name='fs_requests', to='OnlineBroker.agentclient')),
            ],
            options={
                'verbose_name': '目录浏览请求',
                'verbose_name_plural': '目录浏览请求',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='OnlineBroke_client__f2c0ac_idx')],
            },
        ),
    ]
