# Generated by Django 5.2.9 on 2026-06-29 01:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBroker', '0016_fs_browse_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('tool_name', models.CharField(max_length=128)),
                ('tool_input', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '待应答'), ('allowed', '已允许'), ('denied', '已拒绝')], default='pending', max_length=16)),
                ('remember', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='OnlineBroker.conversation')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='OnlineBroker.task')),
            ],
            options={
                'verbose_name': '工具审批请求',
                'verbose_name_plural': '工具审批请求',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'status'], name='OnlineBroke_convers_2f7499_idx')],
            },
        ),
    ]
