# Generated by Django 5.2.9 on 2026-06-29 03:49

import OnlineBroker.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBroker', '0017_permission_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_path', models.CharField(help_text='PC 上的源文件绝对路径', max_length=4096)),
                ('filename', models.CharField(blank=True, max_length=512)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', '待上传'), ('ready', '可下载'), ('failed', '失败')], default='pending', max_length=16)),
                ('agent_initiated', models.BooleanField(default=False)),
                ('blob', models.FileField(blank=True, null=True, upload_to=OnlineBroker.models._file_transfer_upload_to)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_transfers', to='OnlineBroker.agentclient')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_transfers', to='OnlineBroker.conversation')),
            ],
            options={
                'verbose_name': '文件传输',
                'verbose_name_plural': '文件传输',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='OnlineBroke_client__e23f81_idx')],
            },
        ),
    ]
