# Generated by Django 5.2.9 on 2026-06-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBroker', '0018_file_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsbrowserequest',
            name='include_files',
            field=models.BooleanField(default=False),
        ),
    ]
