# Generated by Django 5.2.9 on 2026-06-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBroker', '0019_fsbrowse_include_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='always_allow_tools',
            field=models.JSONField(blank=True, default=list, help_text='本会话内总是允许的工具名列表'),
        ),
    ]
