# Generated by Django 5.2.9 on 2026-06-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBroker', '0020_conversation_always_allow_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsbrowserequest',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs_requests', to='OnlineBroker.conversation'),
        ),
        migrations.AddField(
            model_name='fsbrowserequest',
            name='root_path',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='fsbrowserequest',
            name='path',
            field=models.CharField(blank=True, help_text='请求列出的目录；空表示起点（root 或主目录）', max_length=4096),
        ),
    ]
