# Generated by Django 5.2.9 on 2026-06-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBroker', '0021_fsbrowse_root_confinement'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetransfer',
            name='root_path',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
