# Generated by Django 5.2.9 on 2026-06-30 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineBroker', '0022_filetransfer_root_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerClientToken',
            fields=[
                ('key', models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Broker 客户端 Token',
                'verbose_name_plural': 'Broker 客户端 Token',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'created_at'], name='task_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'heartbeat_at'], name='task_status_heartbeat_idx'),
        ),
        migrations.AddField(
            model_name='brokerclienttoken',
            name='credential',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='OnlineBroker.brokerclientcredential'),
        ),
    ]
